# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Travelog
author: Christopher Shen
author_link: 
author_description: A lonely engineer
email: chrisshen@gatech.edu
description: > # this means to ignore newlines until "baseurl:"
  A travel blog.
baseurl: "travelog" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site 


# Picturefill
# A responsive image polyfill: http://scottjehl.github.io/picturefill/
picturefill: false

# Typography
# To use, publish a kit and enter the ID here. If you do not wish to use Typekit,
# leave this ID blank
typekit_kit_id: kwf5dox

# Build settings
gems: [jekyll-paginate]
markdown: kramdown
permalink: /posts/:title # Post permalink

# Pagination
paginate: 3

# Sass
sass:
    style: :compressed
